In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [20]:
notebook_dir = os.getcwd()
csv_path = os.path.join(notebook_dir, '..', 'data', 'raw', 'stroke.csv')

In [21]:
stroke_dataset = pd.read_csv(csv_path)

In [22]:
print(stroke_dataset.columns)

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [23]:
stroke_table = {
    "Name": ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
    "Unit": ['no unit', 'category', 'years', 'binary', 'category', 'category', 'category', 
             'category','mg/dL', 'kg/m²', 'category', 'binary']
             }
stroke_table = pd.DataFrame(stroke_table)
display(stroke_table)

                 Name      Unit
0                  id   no unit
1              gender  category
2                 age     years
3        hypertension    binary
4       heart_disease  category
5        ever_married  category
6           work_type  category
7      Residence_type  category
8   avg_glucose_level     mg/dL
9                 bmi     kg/m²
10     smoking_status  category
11             stroke    binary

In [24]:
print(f"Stroke dataset shape: {stroke_dataset.shape}")
stroke_dataset.sample(10)

Stroke dataset shape: (5110, 12)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
3178,64597,Female,33.0,0,0,Yes,Private,Rural,73.20,28.9,Unknown,0
308,40181,Female,30.0,0,0,Yes,Private,Urban,61.45,36.7,smokes,0
730,11176,Male,9.0,0,0,No,children,Rural,85.02,16.3,Unknown,0
4904,22417,Female,5.0,0,0,No,children,Rural,80.93,24.8,Unknown,0
3036,25674,Male,40.0,0,0,Yes,Private,Urban,104.64,24.9,Unknown,0
1456,41402,Male,62.0,0,0,Yes,Self-employed,Urban,78.99,45.5,never smoked,0
2304,58253,Male,5.0,0,0,No,children,Urban,71.92,18.2,Unknown,0
1147,32687,Male,37.0,0,0,Yes,Private,Rural,78.42,29.9,never smoked,0
423,67431,Female,52.0,0,0,Yes,Private,Urban,73.73,34.4,formerly smoked,0
964,59336,Male,66.0,1,0,Yes,Private,Rural,74.90,32.1,never smoked,0

In [25]:
print("Stroke dataset info:")
stroke_dataset.info()

Stroke dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [26]:
print(stroke_dataset.dtypes)

id                     int64
gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [27]:
stroke_dataset['gender'] = stroke_dataset['gender'].astype('category')
stroke_dataset['heart_disease'] = stroke_dataset['heart_disease'].astype('bool')
stroke_dataset['ever_married'] = stroke_dataset['ever_married'].astype('category')
stroke_dataset['work_type'] = stroke_dataset['work_type'].astype('category')
stroke_dataset['Residence_type'] = stroke_dataset['Residence_type'].astype('category')
stroke_dataset['smoking_status'] = stroke_dataset['smoking_status'].astype('category')
stroke_dataset['hypertension'] = stroke_dataset['hypertension'].astype('bool')
stroke_dataset['stroke'] = stroke_dataset['stroke'].astype('bool')

In [28]:
duplicates = stroke_dataset[stroke_dataset.duplicated(keep=False)]
sorted_duplicates = duplicates.sort_values(list(duplicates.columns))
display(sorted_duplicates)

Empty DataFrame
Columns: [id, gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke]
Index: []

In [29]:
stroke_dataset.describe()

                 id          age  avg_glucose_level          bmi
count   5110.000000  5110.000000        5110.000000  4909.000000
mean   36517.829354    43.226614         106.147677    28.893237
std    21161.721625    22.612647          45.283560     7.854067
min       67.000000     0.080000          55.120000    10.300000
25%    17741.250000    25.000000          77.245000    23.500000
50%    36932.000000    45.000000          91.885000    28.100000
75%    54682.000000    61.000000         114.090000    33.100000
max    72940.000000    82.000000         271.740000    97.600000

In [30]:
stroke_dataset[stroke_dataset['age'] <= 18]

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
162,69768,Female,1.32,False,False,No,children,Urban,70.37,NaN,Unknown,True
245,49669,Female,14.00,False,False,No,children,Rural,57.93,30.9,Unknown,True
249,30669,Male,3.00,False,False,No,children,Rural,95.12,18.0,Unknown,False
251,16523,Female,8.00,False,False,No,Private,Urban,110.89,17.6,Unknown,False
253,46136,Male,14.00,False,False,No,Never_worked,Rural,161.28,19.1,Unknown,False
...,...,...,...,...,...,...,...,...,...,...,...,...
5094,28048,Male,13.00,False,False,No,children,Urban,82.38,24.3,Unknown,False
5095,68598,Male,1.08,False,False,No,children,Rural,79.15,17.4,Unknown,False
5098,579,Male,9.00,False,False,No,children,Urban,71.88,17.5,Unknown,False
5103,22127,Female,18.00,False,False,No,Private,Urban,82.85,46.9,Unknown,False
5104,14180,Female,13.00,False,False,No,children,Rural,103.08,18.6,Unknown,False

In [31]:
stroke_dataset = stroke_dataset[stroke_dataset['age'] >= 18]

In [32]:
stroke_dataset.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  181
smoking_status         0
stroke                 0
dtype: int64

In [33]:
stroke_dataset['bmi'].fillna(stroke_dataset['bmi'].median(), inplace=True)

In [34]:
print(stroke_dataset.shape)

(4254, 12)

In [35]:
print(stroke_dataset['stroke'].value_counts())
print(stroke_dataset['stroke'].value_counts(normalize=True))

stroke
False    4007
True      247
Name: count, dtype: int64
stroke
False    0.941937
True     0.058063
Name: proportion, dtype: float64

In [36]:
stroke_dataset.to_csv('../data/processed/stroke_processed.csv', index=False)